### ISSUE TITLE
OOM in LSBDetectionTask

### ISSUE THREAD

**Issue by huangyz0918** [huangyz0918/AndroidWM#2]
When using `StringBuilder` to build a very long string from an array,  the method `intArrayToString` will throws an Out of Memory exception.

### Solution
divide the input array to multiple subarrays, and use different StringBuilder to append the strings together.

**Comment by huangyz0918** [comment]
The image loaded by Glide works well, but loaded via xml does not, it will throws an OOM.

**Comment by huangyz0918** [comment]
```java
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 10485772 byte allocation with 9292036 free bytes and 8MB until OOM
        at com.watermark.androidwm.task.LSBWatermarkTask.doInBackground(LSBWatermarkTask.java:122)
        at com.watermark.androidwm.task.LSBWatermarkTask.doInBackground(LSBWatermarkTask.java:40)

```

**Comment by huangyz0918** [comment]
Closed via setting the max image size = 1024.
