### ISSUE TITLE
IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by huangyz0918** [huangyz0918/AndroidWM#7]
```java
Caused by: java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:720)
        at com.watermark.androidwm.utils.BitmapUtils.resizeBitmap(BitmapUtils.java:153)
        at com.watermark.androidwm.Watermark.createWatermarkImage(Watermark.java:153)
        at com.watermark.androidwm.Watermark.<init>(Watermark.java:94)
        at com.watermark.androidwm.WatermarkBuilder.setInvisibleWMListener(WatermarkBuilder.java:253)
        at com.example.huangyz0918.myapplication.MainActivity.onCreate(MainActivity.java:35)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)

```

in method `resizeBitmap()`.

**Comment by huangyz0918** [comment]
Closed.
