### ISSUE TITLE
Requested array size exceeds VM limit 

### ISSUE THREAD

**Issue by huangyz0918** [huangyz0918/AndroidWM#8]
In the `LSBWatermarkTask` : 

```java
  int[] rebuiltPixels = new int[backgroundPixels.length];
```

We will get a out of memory error while init a large int array.

```java
  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 10485772 byte allocation with 9612332 free bytes and 9MB until OOM
        at com.watermark.androidwm.task.LSBWatermarkTask.doInBackground(LSBWatermarkTask.java:122)
        at com.watermark.androidwm.task.LSBWatermarkTask.doInBackground(LSBWatermarkTask.java:40)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
```

Consider using a `BitSet` to refactor the code.

**Comment by huangyz0918** [comment]
Closed via setting the max image size = 1024.
